<?php

return [
    [
        'name' => 'Moka Tunis',
        'cuisine' => 'Mediterranean',
        'category' => 'brasserie',
        'address' => 'Rue de Marseille, Centre Ville',
        'city' => 'Tunis',
        'phone' => '+216 71 240 118',
        'priceRange' => '€€',
        'lat' => 36.8008,
        'lng' => 10.1815,
        'tags' => 'Cafe,Brunch,Central',
        'image' => 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
        'description' => 'A lively central spot for brunch plates, coffee, and Mediterranean comfort dishes.',
        'openHours' => 'Daily : 8AM-11PM',
    ],
    [
        'name' => 'La Terrasse de Carthage',
        'cuisine' => 'Mediterranean',
        'category' => 'gastronomique',
        'address' => 'Byrsa Hill',
        'city' => 'Carthage',
        'phone' => '+216 71 730 444',
        'priceRange' => '€€€',
        'lat' => 36.8529,
        'lng' => 10.3238,
        'tags' => 'View,Terrace,Seafood',
        'image' => 'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=800&q=80',
        'description' => 'Sea-view dining near historic Carthage with grilled fish, seasonal salads, and refined service.',
        'openHours' => 'Tue-Sun : 12PM-11PM',
    ],
    [
        'name' => 'Hammamet Garden Grill',
        'cuisine' => 'Tunisian',
        'category' => 'brasserie',
        'address' => 'Zone Touristique Nord',
        'city' => 'Hammamet',
        'phone' => '+216 72 280 707',
        'priceRange' => '€€',
        'lat' => 36.4017,
        'lng' => 10.6139,
        'tags' => 'Garden,Grill,Family',
        'image' => 'https://images.unsplash.com/photo-1544148103-0773bf10d330?w=800&q=80',
        'description' => 'A relaxed garden restaurant with charcoal grills, salads, and family-style Tunisian plates.',
        'openHours' => 'Daily : 11AM-10:30PM',
    ],
    [
        'name' => 'Sushi Marsa',
        'cuisine' => 'Asian',
        'category' => 'asiatique',
        'address' => 'Avenue Habib Bourguiba',
        'city' => 'La Marsa',
        'phone' => '+216 71 980 221',
        'priceRange' => '€€',
        'lat' => 36.8792,
        'lng' => 10.3272,
        'tags' => 'Sushi,Modern,Takeaway',
        'image' => 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800&q=80',
        'description' => 'Modern sushi rolls, rice bowls, and light Asian plates a few streets from the beach.',
        'openHours' => 'Daily : 12PM-11PM',
    ],
    [
        'name' => 'Pasta Marina Monastir',
        'cuisine' => 'Italian',
        'category' => 'italien',
        'address' => 'Port de Plaisance',
        'city' => 'Monastir',
        'phone' => '+216 73 462 808',
        'priceRange' => '€€',
        'lat' => 35.7792,
        'lng' => 10.8310,
        'tags' => 'Pasta,Marina,Sunset',
        'image' => 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=800&q=80',
        'description' => 'Handmade pasta, pizzas, and seafood risotto overlooking the marina.',
        'openHours' => 'Daily : 12PM-11:30PM',
    ],
    [
        'name' => 'Blue Net Sousse',
        'cuisine' => 'Seafood',
        'category' => 'fruits-de-mer',
        'address' => 'Port El Kantaoui',
        'city' => 'Sousse',
        'phone' => '+216 73 348 909',
        'priceRange' => '€€€',
        'lat' => 35.8920,
        'lng' => 10.5946,
        'tags' => 'Seafood,Harbor,Grill',
<<<<<<< HEAD
        'image' => 'https://images.unsplash.com/photo-1515669097368-22e68427d265?w=800&q=80',
=======
<<<<<<< HEAD
        'image' => 'https://images.unsplash.com/photo-1515669097368-22e68427d265?w=800&q=80',
=======
        'image' => 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&q=80',
>>>>>>> df34791d4b40b7fc6586c4e6c6ecd09ede24f718
>>>>>>> 9f33d9882a7e691571e96025575b7eef87d6352b
        'description' => 'Fresh fish displays, grilled shellfish, and harbor-side service in Port El Kantaoui.',
        'openHours' => 'Daily : 12PM-11PM',
    ],
    [
        'name' => 'Bizerte Burger Lab',
        'cuisine' => 'Street Food',
        'category' => 'street-food',
        'address' => 'Avenue Habib Bourguiba',
        'city' => 'Bizerte',
        'phone' => '+216 72 430 502',
        'priceRange' => '€',
        'lat' => 37.2746,
        'lng' => 9.8739,
        'tags' => 'Burger,Fast,Casual',
        'image' => 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80',
        'description' => 'Casual burger counter with local sauces, crispy fries, and late-night service.',
        'openHours' => 'Daily : 11AM-1AM',
    ],
    [
        'name' => 'Kairouan Heritage Table',
        'cuisine' => 'Tunisian',
        'category' => 'gastronomique',
        'address' => 'Medina Quarter',
        'city' => 'Kairouan',
        'phone' => '+216 77 230 321',
        'priceRange' => '€€',
        'lat' => 35.6771,
        'lng' => 10.1008,
        'tags' => 'Medina,Traditional,Lamb',
        'image' => 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80',
        'description' => 'A heritage dining room serving lamb, couscous, makroudh, and regional classics.',
        'openHours' => 'Mon-Sat : 12PM-9PM',
    ],
    [
        'name' => 'Tozeur Palm Kitchen',
        'cuisine' => 'Tunisian',
        'category' => 'africaine',
        'address' => 'Oasis Road',
        'city' => 'Tozeur',
        'phone' => '+216 76 452 802',
        'priceRange' => '€€',
        'lat' => 33.9197,
        'lng' => 8.1335,
        'tags' => 'Oasis,Dates,Slow Food',
        'image' => 'https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=800&q=80',
        'description' => 'Oasis cooking with dates, lamb, local bread, and slow stews under palm shade.',
        'openHours' => 'Daily : 10AM-9PM',
    ],
    [
        'name' => 'Djerba Spice House',
        'cuisine' => 'African',
        'category' => 'africaine',
        'address' => 'Houmt Souk Market',
        'city' => 'Medenine',
        'phone' => '+216 75 651 404',
        'priceRange' => '€',
        'lat' => 33.8756,
        'lng' => 10.8574,
        'tags' => 'Spices,Djerbian Rice,Market',
        'image' => 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&q=80',
        'description' => 'Market-side Djerbian rice, seafood stews, and spice-forward island cooking.',
        'openHours' => 'Daily : 9AM-8PM',
    ],
    [
        'name' => 'Ariana Noodle Bar',
        'cuisine' => 'Asian',
        'category' => 'asiatique',
        'address' => 'Ennasr 2',
        'city' => 'Ariana',
        'phone' => '+216 71 820 550',
        'priceRange' => '€€',
        'lat' => 36.8663,
        'lng' => 10.1647,
        'tags' => 'Noodles,Ramen,Quick',
        'image' => 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&q=80',
        'description' => 'Ramen, stir-fried noodles, dumplings, and quick Asian lunches in Ennasr.',
        'openHours' => 'Daily : 12PM-10:30PM',
    ],
    [
        'name' => 'Sfax Olive Yard',
        'cuisine' => 'Tunisian',
        'category' => 'brasserie',
        'address' => 'Route de Tunis',
        'city' => 'Sfax',
        'phone' => '+216 74 245 777',
        'priceRange' => '€€',
        'lat' => 34.7532,
        'lng' => 10.7568,
        'tags' => 'Olive Oil,Grill,Local',
        'image' => 'https://images.unsplash.com/photo-1544148103-0773bf10d330?w=800&q=80',
        'description' => 'Grilled meats, olive oil tastings, and local Sfaxian plates in a courtyard setting.',
        'openHours' => 'Tue-Sun : 11AM-10PM',
    ],
];
